[build]
  publish = "_site"
  command = "DEBUG=* eleventy"

[[headers]]
# Define which paths this specific [[headers]] block will cover.
  for = "/*"

  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "frame-ancestors https://*.iamkaska.com"

    # Multi-value headers are expressed with multi-line strings.
	cache-control = '''
	max-age=63072000,
	no-cache,
	no-store,
	must-revalidate'''


  Strict-Transport-Security: max-age=63072000; includeSubDomains; preload